apiVersion: v1
kind: Secret
type: "Opaque"
metadata:
  name: "{{ .Chart.Name }}-traefik"
  namespace: "{{ .Release.Namespace }}"
  labels:
    "app.kubernetes.io/name": "{{ .Chart.Name }}"
    "app.kubernetes.io/instance": "{{ .Chart.Name }}-traefik"
data:
  AWS_ACCESS_KEY_ID: "{{ .Values.traefik.acme.aws.accessKey | b64enc }}"
  AWS_SECRET_ACCESS_KEY: "{{ .Values.traefik.acme.aws.secretKey | b64enc }}"
  AWS_REGION: "{{ .Values.traefik.acme.aws.region | b64enc }}"
  AWS_HOSTED_ZONE_ID: "{{ .Values.traefik.acme.aws.hostedZone | b64enc }}"
