include(FindPackageHandleStandardArgs)

if (NOT TARGET Png)
    find_library(PNG_LIBRARIES_RELEASE NAMES png png16 libpng16)
    if (MSVC)
        find_library(PNG_LIBRARIES_DEBUG NAMES pngd png16d libpng16d)
    endif ()
    find_path(PNG_INCLUDE_DIR NAMES png.h)
    add_library(Png STATIC IMPORTED)
    set_target_properties(Png PROPERTIES INTERFACE_INCLUDE_DIRECTORIES "${PNG_INCLUDE_DIR}")
    if (MSVC)
        set_target_properties(Png PROPERTIES IMPORTED_LOCATION_RELEASE ${PNG_LIBRARIES_RELEASE})
        set_target_properties(Png PROPERTIES IMPORTED_LOCATION_DEBUG ${PNG_LIBRARIES_DEBUG})
    else ()
        set_target_properties(Png PROPERTIES IMPORTED_LOCATION ${PNG_LIBRARIES_RELEASE})
    endif ()
endif ()

if (MSVC)
    find_package_handle_standard_args(Png DEFAULT_MSG PNG_LIBRARIES_RELEASE PNG_LIBRARIES_DEBUG PNG_INCLUDE_DIR)
else ()
    find_package_handle_standard_args(Png DEFAULT_MSG PNG_LIBRARIES PNG_INCLUDE_DIR)
endif ()
