log:
  level: DEBUG

access: {}

api:
  insecure: false
  dashboard: false

entryPoints:
  http:
    address: ":8080"
  https:
    address: ":8443"

providers:
  file:
    filename: "/tmp/matchmaker/traefik-local.yaml"

tls:
  stores:
    default:
      defaultCertificate:
        certFile: /tmp/matchmaker/certs/server.crt
        keyFile: /tmp/matchmaker/certs/server.key
  certificates:
    - certFile: /tmp/matchmaker/certs/server.crt
      keyFile: /tmp/matchmaker/certs/server.key
#  domains:
 #   - main: "matchmaker.lan"

http:
  routers:
    matchmaker:
      rule: "Host(`matchmaker.lan`)"
      service: "matchmaker"
      entryPoints:
        - https
      tls: true
  services:
    matchmaker:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:8000"
