log:
  level: "INFO"

api:
  insecure: false
  dashboard: false

entryPoints:
  web:
    address: ":8080"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":8443"

certificatesResolvers:
  letsencrypt:
    acme:
      email: "email@matusnovak.com"
      storage: "/acme/acme.json"
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      dnsChallenge:
        provider: "route53"
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"

providers:
  file:
    filename: "/etc/traefik/dynamic.yaml"
