apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: "{{ .Chart.Name }}-api"
  namespace: "{{ .Release.Namespace }}"
  labels:
    "app.kubernetes.io/name": "{{ .Chart.Name }}"
    "app.kubernetes.io/instance": "{{ .Chart.Name }}-api"
spec:
  entryPoints:
    - web
    - websecure
  tls:
    certResolver: letsencrypt
  routes:
    - match: Host(`{{ .Values.domain }}`)
      kind: Rule
      services:
       - name: "{{ .Chart.Name }}-api"
         namespace: "{{ .Release.Namespace }}"
         port: api
