apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "{{ .Chart.Name }}-api"
  namespace: "{{ .Release.Namespace }}"
  labels:
    "app.kubernetes.io/name": "{{ .Chart.Name }}"
    "app.kubernetes.io/instance": "{{ .Chart.Name }}-api"
rules:
  - apiGroups:
      - "extensions"
    resources:
      - "podsecuritypolicies"
    verbs:
      - "use"
    resourceNames:
      - "{{ .Chart.Name }}-api"
