apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}-api"
  namespace: "{{ .Release.Namespace }}"
  labels:
    "app.kubernetes.io/name": "{{ .Chart.Name }}"
    "app.kubernetes.io/instance": "{{ .Chart.Name }}-api"
spec:
  type: {{ .Values.api.service.type }}
  selector:
    "app.kubernetes.io/name": "{{ .Chart.Name }}"
    "app.kubernetes.io/instance": "{{ .Chart.Name }}-api"
  ports:
    - port: {{ .Values.api.http.port }}
      targetPort: api
      protocol: TCP
      name: api
