set(CPACK_OUTPUT_FILE_PREFIX "release")
set(CPACK_PACKAGE_FILE_NAME "${PROJECT_NAME}-${VERSION_STRING}-${CMAKE_SYSTEM_NAME}")
set(CPACK_INCLUDE_TOPLEVEL_DIRECTORY OFF)
if (MSVC)
    set(CPACK_GENERATOR "ZIP;WIX" CACHE STRING "Generators to support")
elseif (APPLE)
    set(CPACK_GENERATOR "ZIP;Bundle" CACHE STRING "Generators to support")
else ()
    set(CPACK_GENERATOR "TGZ" CACHE STRING "Generators to support")
endif ()

if (MSVC)
    set(PROJECT_UUID "ed51a2af-8380-4e87-9cf3-bef69f58493c")
    string(UUID CPACK_WIX_UPGRADE_GUID
            NAMESPACE "${PROJECT_UUID}" NAME "${PROJECT_NAME}" TYPE MD5)
    string(UUID CPACK_WIX_PRODUCT_GUID
            NAMESPACE "${PROJECT_UUID}" NAME "${VERSION_STRING}" TYPE MD5)
    set(CPACK_WIX_PRODUCT_ICON "${CMAKE_CURRENT_SOURCE_DIR}/logo/logo-icon.ico")
    set(CPACK_WIX_UI_BANNER "${CMAKE_CURRENT_SOURCE_DIR}/logo/wix-banner.png")
    set(CPACK_WIX_UI_DIALOG "${CMAKE_CURRENT_SOURCE_DIR}/logo/wix-dialog.png")
    set(CPACK_WIX_PROGRAM_MENU_FOLDER "Temporary Escape")
    set(CPACK_WIX_ARCHITECTURE "x64")
    set(CPACK_WIX_CULTURES "en-US")
    set(CPACK_WIX_LICENSE_RTF "${CMAKE_CURRENT_LIST_DIR}/windows/LICENSE.rtf")
elseif (APPLE)
    set(CPACK_BUNDLE_NAME "TemporaryEscape")
    set(CPACK_BUNDLE_PLIST "${CMAKE_CURRENT_LIST_DIR}/macos/Info.plist")
    set(CPACK_BUNDLE_ICON "${CMAKE_CURRENT_SOURCE_DIR}/logo/logo-icon.icns")
    set(CPACK_BUNDLE_STARTUP_COMMAND "${CMAKE_CURRENT_LIST_DIR}/macos/TemporaryEscape.sh")
endif ()

set(CPACK_PACKAGE_INSTALL_DIRECTORY "Temporary Escape")
include(CPack)
