name: build
on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: 'Build - Windows'
            os: windows-latest
            config: 'Release'
            cpack: 'ZIP'
            configurePreset: 'msbuild'
            buildPreset: 'msbuild'
            vcpkgCommitId: 'f14984af3738e69f197bf0e647a8dca12de92996'
            vulkanSdkVer: '1.3.239.0'
            vcpkgDir: 'C:\vcpkg'

          - name: 'Build - Linux'
            os: ubuntu-latest
            config: 'Release'
            cpack: 'TGZ'
            configurePreset: 'ninja'
            buildPreset: 'ninja'
            vcpkgCommitId: 'f14984af3738e69f197bf0e647a8dca12de92996'
            vulkanSdkVer: '1.3.239.0'
            vcpkgDir: '/usr/local/share/vcpkg'

    #      - name: 'Build - Mac OSX'
    #        os: macos-latest
    #        config: 'Release'
    #        cpack: 'ZIP'
    #        configurePreset: 'ninja'
    #        buildPreset: 'ninja - ninja'

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Dependencies
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt-get install -y \
              ninja-build clang llvm libxinerama-dev libxcursor-dev xorg-dev \
              libglu1-mesa-dev libc6-dev linux-libc-dev liburing-dev
          elif [ "$RUNNER_OS" == "macOS" ]; then
            brew install ninja llvm
          fi

      - name: Configure Vcpkg
        shell: bash
        run: |
          cd ${{ matrix.vcpkgDir }}
          git fetch origin
          git reset --hard origin/master
          if [ "$RUNNER_OS" == "Windows" ]; then
            ./bootstrap-vcpkg.bat
          else
            ./bootstrap-vcpkg.sh
          fi

      - name: Setup Vulkan - Windows
        if: runner.os == 'Windows'
        run: |
          $ProgressPreference = 'SilentlyContinue'
          Invoke-WebRequest -Uri "https://sdk.lunarg.com/sdk/download/${{ matrix.vulkanSdkVer }}/windows/VulkanSDK-${{ matrix.vulkanSdkVer }}-Installer.exe" -OutFile VulkanSDK.exe
          .\VulkanSDK.exe --root C:\VulkanSDK  --accept-licenses --default-answer --confirm-command install
          Remove-Item .\VulkanSDK.exe

      - name: Setup Vulkan - Linux
        if: runner.os == 'Linux'
        run: |
          wget -O vulkansdk.tar.gz -q https://sdk.lunarg.com/sdk/download/${{ matrix.vulkanSdkVer }}/linux/vulkansdk-linux-x86_64-${{ matrix.vulkanSdkVer }}.tar.gz
          tar -xzf vulkansdk.tar.gz
          sudo mv ./${{ matrix.vulkanSdkVer }}/ /opt/vulkan-sdk
          rm vulkansdk.tar.gz

      - name: Cache vcpkg directory
        uses: actions/cache@v2
        with:
          path: |
            build/vcpkg_installed
            ${{ matrix.vcpkgDir }}/packages
          key: ${{ runner.os }}-vcpkg-${{ hashFiles('vcpkg.json') }}

      - name: Configure - Windows
        env:
          VCPKG_ROOT: "${{ matrix.vcpkgDir }}"
          VULKAN_SDK: "C:/VulkanSDK"
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          cmake --preset "${{ matrix.configurePreset }}" -DCMAKE_BUILD_TYPE=Release -DTEMPORARY_ESCAPE_BUILD_TESTS=ON

      - name: Configure - Linux
        env:
          VCPKG_ROOT: "${{ matrix.vcpkgDir }}"
        shell: bash
        run: |
          source /opt/vulkan-sdk/setup-env.sh
          cmake --preset "${{ matrix.configurePreset }}" -DCMAKE_BUILD_TYPE=Release -DTEMPORARY_ESCAPE_BUILD_TESTS=ON

      - name: Build
        shell: bash
        run: |
          cmake --build --preset "${{ matrix.buildPreset }}" --parallel --target all

      - name: Unit Test
        shell: bash
        run: |
          cd ./build
          ctest --config Release --verbose
